export HTTPS_KEY=''
export HTTPS_CERT=''
export HTTPS_PORT=443

export OST_GETH_UTILITY_RPC_PROVIDER='http://localhost:9546'

export OST_UTILITY_DEPLOYER_ADDR=''
export OST_UTILITY_DEPLOYER_PASSPHRASE='testtest'

export OST_UTILITY_REGISTRAR_ADDR=''
export OST_UTILITY_REGISTRAR_PASSPHRASE='testtest'

export OST_UTILITY_GAS_PRICE='0x12A05F200'

export OST_SIMPLE_TOKEN_CONTRACT_ADDR=''

export OST_UTILITY_CHAIN_OWNER_PASSPHRASE='testtest'


export OST_UTILITY_CHAIN_OWNER_ADDR=''

export OST_UTILITY_CHAIN_OWNER_ADDR='0x475b310cc3310a9f752c8b8fb7d021476a18c63d'

export OSTE_CONTRACT_SimpleToken_ADDR='testingContractAddress'